
def transcribe(dna):
    return dna.replace("T", "U")

def translate(rna):
    codon_table = {
        "UUU": "F", "UUC": "F", "UUA": "L", "UUG": "L",
        "UCU": "S", "UCC": "S", "UCA": "S", "UCG": "S",
        "UAU": "Y", "UAC": "Y", "UAA": "Stop", "UAG": "Stop",
        "UGU": "C", "UGC": "C", "UGA": "Stop", "UGG": "W",
        "CUU": "L", "CUC": "L", "CUA": "L", "CUG": "L",
        "CCU": "P", "CCC": "P", "CCA": "P", "CCG": "P",
        "CAU": "H", "CAC": "H", "CAA": "Q", "CAG": "Q",
        "CGU": "R", "CGC": "R", "CGA": "R", "CGG": "R",
        "AUU": "I", "AUC": "I", "AUA": "I", "AUG": "M",
        "ACU": "T", "ACC": "T", "ACA": "T", "ACG": "T",
        "AAU": "N", "AAC": "N", "AAA": "K", "AAG": "K",
        "AGU": "S", "AGC": "S", "AGA": "R", "AGG": "R",
        "GUU": "V", "GUC": "V", "GUA": "V", "GUG": "V",
        "GCU": "A", "GCC": "A", "GCA": "A", "GCG": "A",
        "GAU": "D", "GAC": "D", "GAA": "E", "GAG": "E",
        "GGU": "G", "GGC": "G", "GGA": "G", "GGG": "G"
    }

    protein = ""
    i = 0
    while i < len(rna):
        codon = rna[i:i+3]  #1aa=3codons
        aa = codon_table[codon]
        if aa == "Stop":
            break
        protein += aa
        i += 3  

    return protein

dna = "ATGAGTCGTGACGGCATTAAAGCACAGTCCCCCAGGGTAAACATACACACAACAAAAGGCACTAGAGCGGACTAAGGTACTAACCGGCTTATGCCGAGGCCCATGTCAGCTCGAAGATGGGGGCGCGTTGAGGCGACAGGTAGCATTCGCATCGAATAAGAGCTTTGATTAGGGCGATGTACAGCCTGGAAGGCAAAAACATGACGATCGCTCCCTTACGCCTAACAGTATTTCAATACATCCTTAACCTTTCTGGCCTGTGTCGGTACTCGAAAACGCCAGATTTTCTCCACCATCCTAGAGAACTTAAACGTATTCGTTCCTTAGGACTGTTAAACATCTCCCATATGGGTTTTGTGACCCTGTCGTGCACAGTCGATATTTTGAGTGGCTGGGGGGTACGACGGCTCTCTGGACTTCGAGCATTTACTTTAGCGCGCCACCGCCACGGGTCCCACATCATCCAGGCGGTACAGAAGAAAGTATAGCTTTTTTATTATCTTTGGATCCTAACAATAGTCCTTATTTGTATCACAGGTTTCCGATAGCATGGCATACGTGCATAGCCAAAGGAAGAGTACAGAAATACTTCGAACTACTGGGAACCAAGGACGAGCCCGCTTCGACCGAGGAACGGGGGGTGCTGTGAATTTTAGGATACGATCGTAAGAGCGCAGGGCGTATGTGGCCATAAATCCGAGTCAGTTGGCGAGGTGCAACATTTATTCGAACGACCAAGGGTGGCAGAATTGGACGGCCTATTGACACAGAAAAATAGGAAGACCTTTAGGGGCAGCGCACTTGCGCAATCCGGTAGAGCCTCAGAAATTGGTGGATTCAGAAAGACAGAGCGGGCTGGCAGATAGACGACATGAGTACCAAGGGCATGCTTCGGGGATGTGCACGATGCCGTATAAATCCGCCACGGCTCGCGAGTCAGACTCGCGACTTTGTATACTGAGTAG"

introns = ["TAGCATGGCATACGTGCATAGCCAAAGGAAGAGTACAGAAATACTTCG", "GTGCTGTGAATTTTA",
"AGAGCGGACTAAGGTACTAACCGGCTTATGCCGAGGCCC",
"TTATTATCTTTGGATC",
"TTTTGTGACCCTGTCG",
"CAATACATCCTTAACCTTTCTGGCC",
"GAAATTGGTGGATTCAGAAAGACAG",
"TAAATCCGAGTCAGTTGGCGAGGTGCAACATTTATTCGAA",
"TTTACTTTAGCGCG",
"TTAAACGTATTCG",
"CCGTATAAATCCGCCACGGCTCGCGAGTCAGA",
"ATCGAATAAGAGCTTTGATTAGGGCGATGTACAGC",
"AGGACGAGCCC",
"ACACAGAAAAATAGGAAG"]

for intron in introns:
    dna = dna.replace(intron, "")
rna = transcribe(dna)

prot = translate(rna)

print(prot)
